export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const LOAD_ALL_TASK = 'LOAD_ALL_TASK';
export const LOAD_ALL_TASK_SUCCESS = 'LOAD_ALL_TASK_SUCCESS';
export const LOAD_ALL_TASK_ERROR = 'LOAD_ALL_TASK_ERROR';

export const LOAD_USER_TASK = 'LOAD_USER_TASK';
export const LOAD_USER_TASK_SUCCESS = 'LOAD_USER_TASK_SUCCESS';
export const LOAD_USER_TASK_ERROR = 'LOAD_USER_TASK_ERROR';

export const LOAD_SELECTED_TASK = 'LOAD_SELECTED_TASK';
export const LOAD_SELECTED_TASK_SUCCESS = 'LOAD_SELECTED_TASK_SUCCESS';
export const LOAD_SELECTED_TASK_ERROR = 'LOAD_SELECTED_TASK_ERROR';

export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
export const CHANGE_TASK_STATUS_ERROR = 'CHANGE_TASK_STATUS_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';