export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOAD_TASK = 'LOAD_TASK';
export const LOAD_ACTIVE_TASK = 'LOAD_ACTIVE_TASK';
export const LOAD_TASK_SUCCESS = 'LOAD_TASK_SUCCESS';
export const CHANGE_TASK_STATUS = 'CHANGE_CHANGE_TASK_STATUS_STATUS';
